#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::index

# property.index:
#   path: /biens
#   controller: App\Controller\PropertyController::index

logout:
  path: /logout